spring:
  application:
    name: user-service

  datasource:
    url: jdbc:postgresql://localhost:5433/user_db
    username: myuser
    password: mypassword12345

  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Kolkata

server:
  port: 9020